---
apiVersion: v1
kind: Namespace
metadata:
  name: aws9f
---
#shop svc
apiVersion: v1
kind: Service
metadata:
  name: aws9-svc-shop
  namespace: aws9f
spec:
  selector:
    web: shop-svc
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
#shop deploy
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: shop-deploy
  namespace: aws9f
spec:
  selector:
    matchLabels:
      web: shop-svc
  template:
    metadata: 
      labels:
        web: shop-svc
    spec:
      containers:
      - name: shopctn
        image: hub.aws9.pri/test/shop:blue2
        ports:
          - containerPort: 80
